credentials:
  usernames:
    amont:
      email: amont@gmail.com
      name: Andre Montgomery
      password: '123' # To be replaced with hashed password
    hspence:
      email: hspence@gmail.com
      name: Hunter Spence
      password: '456' # To be replaced with hashed password
cookie:
  expiry_days: 0
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - nick@gmail.com
  
